#!/bin/bash

# Use djds/volitility:cosmic by default
REGISTRY="${REGISTRY:-}"
tag="cosmic"

docker run --rm -it \
    -c 4 \
    -m 4096M \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=unix${DISPLAY}" \
    -v "$(pwd):/home/volatility/data" \
    -v /dev/shm:/dev/shm \
    --name volatility \
    "${REGISTRY}djds/volatility:${tag}" "${@}"
