#!/bin/bash

# Use djds/volatility:latest by default
REGISTRY="${REGISTRY:-}"
tag="latest"

docker run --rm -it \
    -c 4 \
    -m 4096M \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=unix${DISPLAY}" \
    -v "${PWD}:/home/volatility/data" \
    -v /dev/shm:/dev/shm \
    --name volatility \
    "${REGISTRY}djds/volatility:${tag}" "${@}"
