#!/bin/bash

set -euo pipefail

REGISTRY="${REGISTRY:-}"

user='djds'
repo='ftkimager'
tag=${1:-latest}

docker build \
    -t "${REGISTRY}${user}/${repo}:${tag}" .

if [[ "${PUSH:-}" == "true" ]]; then
    docker push "${REGISTRY}${user}/${repo}:${tag}"
fi

# clean up our host environment
unset {GID,ID}
