#!/bin/bash

# Use djds/ftkimager:latest by default
REGISTRY="${REGISTRY:-}"
tag="latest"

docker run --rm -it \
    -c 4 \
    -m 4096M \
    -v /etc/localtime:/etc/localtime:ro \
    -v /dev/shm:/dev/shm \
    -v "${PWD}:/data" \
    --name ftkimager \
    "${REGISTRY}djds/ftkimager:${tag}" "${@}"
