#!/bin/bash

# Use bghost/volitility:cosmic by default
REGISTRY="${REGISTRY:-}"
tag="cosmic"

docker run --rm -it \
    -c 4 \
    -m 4096M \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=unix${DISPLAY}" \
    -v "/var/local/backups/ftk:/data" \
    -v /dev/shm:/dev/shm \
    --device=/dev/sda \
    --name ftkimager \
    "${REGISTRY}djds/ftkimager:${tag}" "${@}"
#    -v "$(pwd):/data" \
