#!/bin/bash

set -euo pipefail

REGISTRY="${REGISTRY:-}"

user='djds'
repo='wireshark'
tag="${1:-latest}"

# set environment vars
ID="${ID:-$(id -u)}"

# build the container:
docker build \
    --build-arg ID="${ID}" \
    -t "${REGISTRY}${user}/${repo}:${tag}" .

if [[ "${PUSH:-}" == "true" ]]; then
    docker push "${REGISTRY}${user}/${repo}:${tag}"
fi

# clean up our host environment
unset ID
