#!/bin/bash

# Use djds/regripper:latest by default
REGISTRY="${REGISTRY:-}"
tag="latest"

docker run --rm -it \
    -c 4 \
    -m 4096M \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=unix${DISPLAY}" \
    -v "$(pwd):/home/regripper/data" \
    -v /dev/shm:/dev/shm \
    --name regripper \
    "${REGISTRY}djds/regripper:${tag}" "${@}"
